CREATE TABLE IF NOT EXISTS "scholarship" (
	"id" serial PRIMARY KEY NOT NULL,
	"application_number" serial NOT NULL,
	"name" text NOT NULL,
	"date_of_birth" timestamp NOT NULL,
	"gender" text NOT NULL,
	"Type" text NOT NULL,
	"category" text NOT NULL,
	"adhar_number" text NOT NULL,
	"father_name" text NOT NULL,
	"father_number" text NOT NULL,
	"mother_name" text,
	"mother_number" text,
	"income" text NOT NULL,
	"father_occupation" text,
	"mother_occupation" text,
	"student_number" text,
	"house_apartment_name" text,
	"place_state" text,
	"post_office" text,
	"country" text NOT NULL,
	"pin_code" text,
	"state" text NOT NULL,
	"district" text NOT NULL,
	"whatsapp_number" text,
	"student_email" text NOT NULL,
	"alternative_number" text,
	"name_of_the_college" text NOT NULL,
	"branch" text NOT NULL,
	"semester" text NOT NULL,
	"hostel_resident" boolean DEFAULT false,
	"cgpa" numeric NOT NULL,
	"bank_name" text NOT NULL,
	"account_number" text NOT NULL,
	"ifsc_code" text NOT NULL,
	"branch_name" text NOT NULL,
	"account_holder" text NOT NULL,
	"photo_url" text,
	"check_url" text,
	"aadhar_card_url" text,
	"college_id_card_url" text,
	"income_url" text,
	"status" text DEFAULT 'Pending',
	"remark" text,
	"application_date" timestamp DEFAULT now(),
	"verifying_admin" text DEFAULT 'null',
	"selecting admin" text DEFAULT 'null',
	"amount_admin" text DEFAULT 'null',
	"admin_reject" text DEFAULT 'null',
	"admin_renewal" text DEFAULT 'null',
	CONSTRAINT "scholarship_application_number_unique" UNIQUE("application_number"),
	CONSTRAINT "scholarship_adhar_number_unique" UNIQUE("adhar_number"),
	CONSTRAINT "scholarship_student_email_unique" UNIQUE("student_email")
);
